### ISSUE TITLE
Artefacts in the calculation of the convex hull

### ISSUE THREAD

**Issue by rhoef** [CellCognition/cecog#221]
The calculation of the convex hull shows a lot of artifacts located preferably in the upper left quadrant of an ROI object.  The Image below is just one example of many.  This affects the calculation of the convex hull features. Number off connected components and anything derived from it.

![artifacts](https://cloud.githubusercontent.com/assets/2571878/19881031/99ca16fa-a002-11e6-9fc6-d4a23c63c573.png)

a) bianry mask of the original image b) convex hull of the binary mask c) difference image

**Comment by ThomasWalter** [comment]
I am not sure that this is an artefact, as all Bresenham lines between any two points need to be inside the resulting set (which is clearly not the case in image a). Do you have other examples? 

A rotational preference is worrying however (and would indeed indicate a bug). Did you test what happens if you turn image a? Perhaps there is a problem in the line scanning for solving ties?

Just to modulate a bit what you said regarding the effect of this: if the problem mainly consists in the many small connected components in the residue image, their number is probably the only feature severely affected. All other features take the size of the connected components (or the size of the residue) into consideration. Take this just as a side-remark: we still have to investigate, whether everything is correct.

**Comment by rhoef** [comment]
What we observe here is mostly noise resulting from pure discretization of smooth outlines.  As already said it is just one example of many.  
[convexhull.zip](https://github.com/CellCognition/cecog/files/566235/convexhull.zip)

![convex](https://cloud.githubusercontent.com/assets/2571878/19924294/567efe12-a0b9-11e6-8625-3e6b0f28b801.png)

I assume that cellcognition  is calculating the convexhull also from a pixelized outlines (i.e. taking the outer most corner of a pixel). Here are two images produced with fiji. 

![polygon](https://cloud.githubusercontent.com/assets/2571878/19925107/8dae16e0-a0bc-11e6-85e0-2f45188fd874.png)
polygons as calculated

![pixelized](https://cloud.githubusercontent.com/assets/2571878/19925145/ccd9f2c6-a0bc-11e6-8786-4a0c1647ca72.png)
pixelized polyons

It is clear if we consider the blue contour (which occupies an area due to pixelazation) as part of the convex hull that we find every now and then additional pixels. 

We could simply erode the convex hull by one pixel before calculating the difference. It might bias the area of the connect components a little.  Taking only the two white areas into account for feature calculation will reflect better the situation that having many additional tiny objects due to noise

**Comment by ThomasWalter** [comment]
> It is clear if we consider the blue contour (which occupies an area due to pixelazation) as part of the convex hull that we find every now and then additional pixels.
I am perfectly fine with finding every now and then additional pixels which are mainly due to the discrete nature of the image support. That's inline with the definition of a convex hull, and that's the limitation of working in Z^2. One solution is to define features accordingly. For instance, there is one feature that applies a size filter (number of connected components with area larger than lambda). Others work directly with the size of the connected components or the size of the sets, so that the effect should be negligible. 

What worries me more is that apparently these "additional pixels" seem to appear more on the left than on the right side. There must be something in the algorithm responsible for this ... maybe it's how ties are handled in the line scanning. This must be corrected in the code (but for this I would test with rotated images). 

> We could simply erode the convex hull by one pixel before calculating the difference. 
Please don't. This would mean that the initial set is not even guaranteed to be a subset of its convex hull. And in any case, that is not a clean solution. 

I can check the algorithm and code when I am back next week (I am still traveling this week).

**Comment by ThomasWalter** [comment]
OK, I checked this. As I suspected, there was a minor bug in the line scanning algorithm. I do not believe that it seriously affects the results. Nevertheless, I corrected this and pushed to the branch `debug_convex_hull`

I did not want to merge, as I do not know how our policy is regarding changes that can affect previous classifiers. Again, I really think that this is minor, but you never know. If everybody is fine I can just merge this to the master. 

The new version does not have any directional preference, but it is also not entirely rotationally invariant (again due to the line scanning algorithm). Also it calculates the convex hull in Z^2, so there are still small components. Again, I do not see that this is a problem. The only feature affected is the number of cc of the difference; all other features use the size in one or the other way. What exactly is your purpose, actually?

**Comment by ThomasWalter** [comment]
Just two examples (original image, convex hull and overlay with the original image in grey): 
![single_points](https://cloud.githubusercontent.com/assets/903009/20345860/5b9847c8-abf9-11e6-9432-e9525e90565b.png)![convex_hull](https://cloud.githubusercontent.com/assets/903009/20345862/61180a94-abf9-11e6-897a-8f4f205af472.png)![convex_hull_overlay](https://cloud.githubusercontent.com/assets/903009/20345868/6a7b7602-abf9-11e6-84b3-03f97584f674.png)
![shape](https://cloud.githubusercontent.com/assets/903009/20345881/775ad480-abf9-11e6-98b8-c47eb370036d.png)![convex_hull_shape](https://cloud.githubusercontent.com/assets/903009/20345888/7d1162c2-abf9-11e6-9b0d-283436e15cc2.png) ![convex_hull_overlay_shape](https://cloud.githubusercontent.com/assets/903009/20345902/86a43224-abf9-11e6-82d1-ec5394a362dc.png)

First example with just a list of points, second example with a shape.

**Comment by ThomasWalter** [comment]
I also exported the function so that the convex hull can be calculated from ccore directly (without having to make feature extraction for candidates etc.)

**Comment by rhoef** [comment]
Added post processing step using this [this function](http://ukoethe.github.io/vigra/doc-release/vigra/group__EdgeDetection.html#ga6f9601dcf8f062b88b8cb80b8fdd76a5).
